(()=>{
  'use strict';
  if(window.__NEXO_FLOTANTE_4517__)return;window.__NEXO_FLOTANTE_4517__=true;
  if(window.self!==window.top)return;
  const pagina=(location.pathname.split('/').pop()||'').toLowerCase();
  if(['index.html','404.html','politica-privacidad.html','terminos-condiciones.html'].includes(pagina))return;
  const $=(s,r=document)=>r.querySelector(s), sleep=ms=>new Promise(r=>setTimeout(r,ms));
  let api=null,abierto=false,escuchando=null,ocupado=false,modoRapido='',oculto=false;
  async function obtenerApi(){if(api)return api;const limite=Date.now()+12000;while(Date.now()<limite){if(window.ConexionFlotas){api=window.ConexionFlotas;return api;}await sleep(80);}throw new Error('NEXO_SIN_CONEXION');}
  function auth(){try{return api?.getAuth?.()||window.ConexionFlotas?.getAuth?.()||{};}catch(_){return{};}}
  function rolActual(){const u=auth().user||{};return String(u.ROL_ID||u.rol_id||u.ROL||u.rol||'').toUpperCase();}
  function puedeGestion(){return ['ROL-SYSADMIN','ROL-ADMIN','ROL-GERENCIA','ADMIN','GERENCIA'].includes(rolActual());}
  function estilo(){
    if($('#nexoFabStyle'))return;const st=document.createElement('style');st.id='nexoFabStyle';st.textContent=`
      @keyframes nexoSpin{to{transform:rotate(360deg)}}@keyframes nexoPulse{0%,100%{opacity:.55;transform:scale(.96)}50%{opacity:1;transform:scale(1.08)}}@keyframes nexoOrbitGesture{0%,100%{transform:translate(0,0) rotate(0) scale(1)}20%{transform:translate(7px,-3px) rotate(8deg) scale(1.035)}45%{transform:translate(1px,-8px) rotate(0) scale(1.065)}70%{transform:translate(-7px,-2px) rotate(-8deg) scale(1.035)}85%{transform:translate(-2px,5px) rotate(3deg) scale(1.02)}}
      #nexoFab{position:fixed;right:18px;bottom:20px;width:80px;height:80px;border:0;border-radius:50%;padding:5px;background:#061b45;z-index:2147482000;cursor:pointer;filter:drop-shadow(0 10px 17px rgba(4,72,160,.4));transition:.18s transform,.18s filter;touch-action:manipulation;isolation:isolate}
      #nexoFab::before{content:'';position:absolute;inset:-5px;border-radius:50%;background:conic-gradient(from 0deg,#0a5fff,#42e8ff,#fff,#1677ff,#061b45,#42e8ff,#0a5fff);animation:nexoSpin 5.2s linear infinite;z-index:-2;box-shadow:0 0 18px #2bdcffaa,0 0 34px #087cff55}
      #nexoFab::after{content:'';position:absolute;inset:-1px;border-radius:50%;background:#061b45;z-index:-1;box-shadow:inset 0 0 0 2px #76efff99}
      #nexoFab:hover{transform:translateY(-3px) scale(1.045);filter:drop-shadow(0 13px 24px rgba(4,102,220,.55))}#nexoFab:hover::before{animation-duration:2.4s}
      #nexoFab.busy::before{animation-duration:.9s;box-shadow:0 0 24px #62f4ff,0 0 48px #0a7cffaa}#nexoFab.attention::before{animation:nexoSpin 2.6s linear infinite,nexoPulse 1.1s ease-in-out infinite}#nexoFab.gesture{animation:nexoOrbitGesture .92s cubic-bezier(.2,.75,.25,1)}
      #nexoFab img{width:100%;height:100%;border-radius:50%;display:block;object-fit:cover;position:relative;z-index:1}
      #nexoFab .ia{position:absolute;right:-4px;bottom:0;background:#071a3b;color:#fff;border:2px solid #68dcff;border-radius:999px;font:800 10px/1 system-ui;padding:5px 6px;box-shadow:0 4px 10px #0005;z-index:3}
      #nexoFab.nexo-hidden{transform:translateX(124px)!important;opacity:0;pointer-events:none;filter:none!important}
      #nexoFabDockToggle{position:fixed;right:103px;bottom:43px;width:30px;height:34px;border:1px solid #8bdfff;border-radius:12px 0 0 12px;background:#062d63;color:#fff;z-index:2147482001;display:grid;place-items:center;padding:0;font:900 22px/1 system-ui;cursor:pointer;box-shadow:0 5px 16px rgba(1,35,78,.24);transition:right .22s ease,transform .22s ease,background .18s ease}
      #nexoFabDockToggle:hover{background:#0b73d9}#nexoFabDockToggle.nexo-hidden{right:-1px;border-radius:12px 0 0 12px;width:34px}
      #nexoFabPanel{position:fixed;right:18px;bottom:116px;width:min(410px,calc(100vw - 24px));max-height:min(690px,calc(100vh - 138px));display:none;flex-direction:column;overflow:hidden;background:#fff;border:1px solid #b8d7ee;border-radius:22px;box-shadow:0 24px 60px rgba(1,35,78,.28);z-index:2147481999;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#102a43}
      #nexoFabPanel.open{display:flex}.nexo-fab-head{display:flex;align-items:center;gap:10px;padding:12px 14px;background:linear-gradient(135deg,#062d63,#0b73d9);color:white}.nexo-fab-head img{width:46px;height:46px;border-radius:50%}.nexo-fab-head b{display:block;font-size:18px}.nexo-fab-head span{font-size:11px;opacity:.92}.nexo-fab-close{margin-left:auto;border:0;background:#ffffff25;color:#fff;border-radius:50%;width:34px;height:34px;font-size:20px;cursor:pointer}
      .nexo-fab-body{padding:12px;overflow:auto}.nexo-fab-status{padding:8px 10px;background:#eef7ff;border:1px solid #cce7ff;border-radius:12px;font-size:12px;margin-bottom:8px}.nexo-fab-powers{display:flex;gap:6px;overflow:auto;padding:0 0 8px}.nexo-power{white-space:nowrap;border:1px solid #c9e3f8;background:#f6fbff;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:700;color:#0b5aa7}
      .nexo-fab-chat{display:flex;flex-direction:column;gap:8px;max-height:330px;overflow:auto;padding:2px 0 9px}.nexo-msg{padding:9px 10px;border-radius:14px;font-size:13px;line-height:1.35;white-space:pre-wrap}.nexo-msg.nexo{background:#eef6ff;border:1px solid #cce3fb}.nexo-msg.user{background:#0b73d9;color:white;margin-left:32px}.nexo-msg.meta{background:#f7fafc;border:1px dashed #bfd2e0;font-size:11px;color:#526b7a}.nexo-doc-card{display:grid;gap:5px;background:#fff;border:1px solid #c8ddeb;border-radius:12px;padding:9px 10px}.nexo-doc-card b{font-size:12px}.nexo-doc-card small{font-size:10px;color:#5d7484}.nexo-doc-card button{border:0;border-radius:9px;background:#eaf4ff;color:#0c5eb2;padding:8px;font-weight:800;cursor:pointer}.nexo-doc-preview{background:#fff;border:1px solid #bdd7e9;border-radius:12px;padding:6px;margin-top:5px}.nexo-doc-preview iframe{width:100%;height:300px;border:0;border-radius:8px}.nexo-doc-preview img{max-width:100%;max-height:300px;display:block;margin:auto;border-radius:8px}
      .nexo-quick-docs{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:4px 0 7px}.nexo-quick-docs button,.nexo-quick-search button{border:1px solid #c7dff3;background:#f4f9ff;color:#0a579f;border-radius:10px;padding:7px 8px;font-size:11px;font-weight:800;cursor:pointer}.nexo-fuel-direct{grid-column:1/-1;background:#fff8e6!important;border-color:#f2c94c!important;color:#7a4b00!important}.nexo-quick-search{display:flex;gap:6px;margin:0 0 7px}.nexo-quick-search button{flex:1}.nexo-quick-toggle{display:flex;align-items:center;justify-content:space-between;margin:4px 0 6px;padding:5px 8px;background:#f7fafc;border:1px solid #d7e3ed;border-radius:10px;font-size:11px;font-weight:800;color:#375568}.nexo-quick-toggle button{width:32px;height:28px;border:0;border-radius:8px;background:#0b5aa7;color:#fff;font-size:18px;font-weight:900;cursor:pointer}.nexo-extra-actions[hidden]{display:none!important}.nexo-mode{margin:0 0 7px;padding:6px 8px;background:#fff8df;border:1px solid #f5d87a;border-radius:9px;font-size:11px;color:#805b00}.nexo-fab-input{width:100%;min-height:68px;resize:vertical;border:1px solid #bfd4e5;border-radius:13px;padding:10px 11px;font:14px system-ui;box-sizing:border-box;outline:none}.nexo-fab-input:focus{border-color:#1d7fe0;box-shadow:0 0 0 3px #1d7fe022}.nexo-fab-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.nexo-fab-actions button{border:0;border-radius:12px;min-height:42px;padding:8px 10px;font-weight:750;cursor:pointer}.nexo-primary{background:#1878e5;color:#fff}.nexo-secondary{background:#eaf4ff;color:#0c5eb2}.nexo-management{background:#062d63!important;color:#fff}.nexo-open{grid-column:1/-1;background:#f0f4f8!important;color:#102a43}.nexo-wide{grid-column:1/-1}
      @media(max-width:640px){#nexoFab{width:66px;height:66px;right:12px;bottom:14px}#nexoFab.nexo-hidden{transform:translateX(106px)!important}#nexoFabDockToggle{right:83px;bottom:31px;width:28px;height:32px;font-size:20px}#nexoFabDockToggle.nexo-hidden{right:-1px;width:34px}#nexoFabPanel{right:12px;bottom:94px;width:calc(100vw - 24px);max-height:calc(100vh - 110px)}.nexo-fab-chat{max-height:38vh}.nexo-quick-docs{grid-template-columns:1fr}.nexo-fab-input{min-height:60px}}@media(prefers-reduced-motion:reduce){#nexoFab::before{animation:none!important}#nexoFab.gesture{animation:none!important}}@media print{#nexoFab,#nexoFabDockToggle,#nexoFabPanel{display:none!important}}
    `;document.head.appendChild(st);
  }
  function mensaje(texto,tipo='nexo'){const chat=$('#nexoFabChat');if(!chat)return;const d=document.createElement('div');d.className=`nexo-msg ${tipo}`;d.textContent=String(texto??'');chat.appendChild(d);chat.scrollTop=chat.scrollHeight;}
  function estado(texto){const n=$('#nexoFabStatus');if(n)n.textContent=texto;}
  function setOcupado(v){ocupado=v;$('#nexoFab')?.classList.toggle('busy',v);$$('#nexoFabPanel button').forEach(b=>{if(!b.classList.contains('nexo-fab-close'))b.disabled=v;});}
  function $$(s,r=document){return Array.from(r.querySelectorAll(s));}
  function limpiarVistaDocumento(){const previa=$('#nexoFabPreview');if(previa)previa.remove();}
  async function abrirDocumentoFlotante(doc){
    const id=String(doc?.ID||'').trim();if(!id)return;estado('Validando permiso y preparando documento…');
    try{const a=await obtenerApi();const r=await a.request('documentFile',{data:{DOCUMENTO_ID:id}});const archivo=r?.archivo||r||{};const url=archivo.url||archivo.URL||archivo.dataUrl||archivo.DATA_URL||doc.URL_TEMPORAL||doc?.VISTA_PREVIA?.URL||'';if(!url)throw new Error('ARCHIVO_NO_DISPONIBLE');
      limpiarVistaDocumento();const caja=document.createElement('div');caja.id='nexoFabPreview';caja.className='nexo-doc-preview';const nombre=archivo.nombre||doc.NOMBRE_ARCHIVO||doc.TIPO||'Documento';const mime=String(archivo.tipoMime||doc.TIPO_MIME||'').toLowerCase();
      const top=document.createElement('div');top.className='nexo-msg meta';top.textContent=`Vista segura · ${nombre} · URL temporal`;caja.appendChild(top);
      if(mime.includes('pdf')||/\.pdf$/i.test(nombre)){const frame=document.createElement('iframe');frame.title=nombre;frame.src=url;caja.appendChild(frame);}else if(mime.startsWith('image/')||/\.(png|jpe?g|webp|gif)$/i.test(nombre)){const img=document.createElement('img');img.alt=nombre;img.src=url;caja.appendChild(img);}else{const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.textContent='Abrir archivo';caja.appendChild(link);}
      $('#nexoFabChat')?.appendChild(caja);$('#nexoFabChat').scrollTop=$('#nexoFabChat').scrollHeight;estado('Documento abierto con validación de permisos.');
    }catch(e){mensaje(`No pude abrir el documento: ${String(e?.message||e||'error')}`,'meta');estado('Nexo disponible');}
  }
  function renderDocumentos(documentos){const chat=$('#nexoFabChat');if(!chat||!Array.isArray(documentos)||!documentos.length)return;const titulo=document.createElement('div');titulo.className='nexo-msg meta';titulo.textContent=`Documentos encontrados: ${documentos.length}`;chat.appendChild(titulo);documentos.slice(0,40).forEach(doc=>{const card=document.createElement('div');card.className='nexo-doc-card';const b=document.createElement('b');b.textContent=doc.TIPO||doc.NOMBRE_ARCHIVO||'Documento';const sm=document.createElement('small');sm.textContent=[doc.FORMATO||doc.TIPO_MIME||'',doc.IDENTIFICACION||'',doc.FECHA_VENCIMIENTO?`Vence ${doc.FECHA_VENCIMIENTO}`:''].filter(Boolean).join(' · ');card.append(b,sm);const url=doc.URL_TEMPORAL||doc?.VISTA_PREVIA?.URL||'';const tiene=doc.TIENE_ARCHIVO!==false&&Boolean(doc.ID||url);const puede=doc.PUEDE_ABRIR!==false&&tiene;if(puede){const btn=document.createElement('button');btn.type='button';const esPdf=doc.ES_PDF===true||String(doc.FORMATO||doc.TIPO_MIME||doc.NOMBRE_ARCHIVO||'').toUpperCase().includes('PDF');btn.textContent=esPdf?'📄 Ver PDF':'Abrir documento';btn.onclick=()=>abrirDocumentoFlotante(doc);card.appendChild(btn);}chat.appendChild(card);});chat.scrollTop=chat.scrollHeight;}
  function prepararModoRapido(modo){modoRapido=modo||'';const campo=$('#nexoFabInput'),aviso=$('#nexoFabMode');if(!campo||!aviso)return;if(modoRapido==='RUT'){campo.value='';campo.placeholder='Digite solo el RUT del conductor, por ejemplo 12.345.678-9';aviso.textContent='Modo licencia por RUT: escriba únicamente el RUT y pulse Enviar.';aviso.hidden=false;}else if(modoRapido==='PATENTE'){campo.value='';campo.placeholder='Digite solo la patente, por ejemplo GLJD31';aviso.textContent='Modo documentos por patente: escriba únicamente la patente y pulse Enviar.';aviso.hidden=false;}else{campo.placeholder='Pregúntame sobre E-fleet o cualquier tema…';aviso.hidden=true;}campo.focus();}
  function consultaConModoRapido(texto){const valor=String(texto||'').trim();if(!valor)return'';if(modoRapido==='RUT')return `Muéstrame la licencia de conducir del RUT ${valor}`;if(modoRapido==='PATENTE')return `Muéstrame los documentos del vehículo patente ${valor}`;return valor;}
  function documentosRespuesta(r){if(Array.isArray(r?.documentos)&&r.documentos.length)return r.documentos;if(Array.isArray(r?.datos?.documentos)&&r.datos.documentos.length)return r.datos.documentos;return[];}
  function programarGesto(){const espera=9000+Math.floor(Math.random()*12000);setTimeout(()=>{const f=$('#nexoFab');if(f&&!abierto&&!ocupado&&!matchMedia('(prefers-reduced-motion: reduce)').matches){f.classList.remove('gesture');void f.offsetWidth;f.classList.add('gesture');setTimeout(()=>f.classList.remove('gesture'),1100);}programarGesto();},espera);}
  async function preguntar(texto){const visible=String(texto||'').trim(),q=consultaConModoRapido(visible);if(!q||ocupado)return;mensaje(modoRapido?`${visible} (${modoRapido==='RUT'?'licencia por RUT':'documentos por patente'})`:q,'user');const campo=$('#nexoFabInput');if(campo)campo.value='';estado('Nexo está analizando con el mismo núcleo del Centro Inteligente…');setOcupado(true);try{const a=await obtenerApi();const r=await a.request('officeAsk',{data:{MENSAJE:q,PREGUNTA:q,ORIGEN:'NEXO_FLOTANTE_WEB',CANAL:'CHAT_FLOTANTE',NIVEL_ANALISIS:'DETALLADO',CONSULTA_PREDETERMINADA:puedeGestion()?'NO':'SI'}});mensaje(r?.respuesta||'Nexo completó la consulta.');if(r?.datos?.tipo)mensaje(`Acción NEXO: ${r.datos.tipo}`,'meta');const docs=documentosRespuesta(r);if(docs.length)renderDocumentos(docs);if(r?.datos?.tipo==='PAQUETE_DOCUMENTOS_PDF'&&docs.length)mensaje('Puedes abrir cada PDF/documento desde las tarjetas mostradas. En Android también puedes generar el PDF consolidado desde este mismo chat.','meta');modoRapido='';const aviso=$('#nexoFabMode');if(aviso)aviso.hidden=true;if(campo)campo.placeholder='Pregúntame sobre E-fleet o cualquier tema…';if(Number(r?.datos?.alertas||0)>0||Number(r?.datos?.notificaciones||0)>0){const f=$('#nexoFab');f?.classList.add('attention');setTimeout(()=>f?.classList.remove('attention'),5000);}estado('NEXO IA · mismo núcleo y poderes del Centro Inteligente');}catch(e){mensaje(`No pude completar la acción: ${String(e?.message||e||'error')}`);estado('Nexo disponible · revise conexión o permisos');}finally{setOcupado(false);}}
  function iniciarVoz(){const campo=$('#nexoFabInput');if(!campo)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){mensaje('El navegador no expone reconocimiento de voz. Puede escribir aquí o usar Nexo IA en Android.');return;}try{escuchando?.abort?.();}catch(_){}const r=new Recognition();escuchando=r;r.lang='es-CL';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>estado('🎙 Nexo está escuchando…');r.onresult=e=>{const t=String(e.results?.[0]?.[0]?.transcript||'').trim();if(t){campo.value=t;preguntar(t);}};r.onerror=()=>estado('No se pudo reconocer la voz · puede escribir');r.onend=()=>{escuchando=null;};try{r.start();}catch(_){estado('Micrófono ocupado');}}
  function prepararAviso(){const campo=$('#nexoFabInput');if(!campo)return;campo.value='Nexo, envía una alerta y notificación a Gerencia: ';campo.focus();campo.setSelectionRange(campo.value.length,campo.value.length);estado('Escriba el mensaje y pulse Enviar. Nexo validará su rol y empresa.');}
  function abrirCentro(){location.href='oficina-virtual.html';}
  function aplicarOculto(v,b,p,t){oculto=Boolean(v);b?.classList.toggle('nexo-hidden',oculto);t?.classList.toggle('nexo-hidden',oculto);if(t){t.textContent=oculto?'‹':'›';t.setAttribute('aria-label',oculto?'Mostrar Nexo IA hacia la izquierda':'Ocultar Nexo IA hacia la derecha');t.title=oculto?'Mostrar Nexo IA':'Ocultar Nexo IA';}if(oculto&&p){abierto=false;p.classList.remove('open');}try{localStorage.setItem('efleet_nexo_fab_oculto',oculto?'1':'0');}catch(_){}}
  function crear(){estilo();const b=document.createElement('button');b.id='nexoFab';b.type='button';b.setAttribute('aria-label','Abrir Nexo IA');b.title='Nexo IA · Centro Inteligente';b.innerHTML='<img src="./nexo-ia-fab.png" alt="Nexo IA"><span class="ia">IA</span>';
    const dock=document.createElement('button');dock.id='nexoFabDockToggle';dock.type='button';dock.textContent='›';dock.setAttribute('aria-label','Ocultar Nexo IA hacia la derecha');dock.title='Ocultar Nexo IA';
    const p=document.createElement('section');p.id='nexoFabPanel';p.setAttribute('aria-label','Nexo IA');p.innerHTML=`<div class="nexo-fab-head"><img src="./nexo-ia-fab.png" alt=""><div><b>Nexo IA</b><span>Chat flotante · mismo núcleo del Centro Inteligente</span></div><button class="nexo-fab-close" type="button" aria-label="Cerrar">×</button></div><div class="nexo-fab-body"><div id="nexoFabStatus" class="nexo-fab-status">Conectando con Nexo…</div><div class="nexo-fab-powers"><span class="nexo-power">Preguntas</span><span class="nexo-power">Análisis</span><span class="nexo-power">Mantenciones</span><span class="nexo-power">Combustible</span><span class="nexo-power">Reportes</span><span class="nexo-power">Alertas</span><span class="nexo-power">Notificaciones</span></div><div id="nexoFabChat" class="nexo-fab-chat"><div class="nexo-msg nexo">Hola. Soy Nexo IA. Puedo ayudarte con E-fleet y también con preguntas generales. Cuando la consulta está fuera del sistema, Gemini responde a través de NEXO sin obtener acceso adicional a tus datos internos.</div></div><div class="nexo-quick-docs"><button type="button" data-nexo-doc-flota>📄 Muéstrame los documentos de mi flota</button><button type="button" data-nexo-doc-vehiculos>🚘 Muéstrame los documentos de mis vehículos</button><button type="button" data-nexo-combustible class="nexo-fuel-direct">⛽ Abrir Combustible</button></div><div class="nexo-quick-search"><button type="button" data-nexo-rut>Licencia por RUT</button><button type="button" data-nexo-patente>Papeles por patente</button></div><div id="nexoFabMode" class="nexo-mode" hidden></div><textarea id="nexoFabInput" class="nexo-fab-input" placeholder="Pregúntame sobre E-fleet o cualquier tema…"></textarea><div class="nexo-fab-actions"><button type="button" class="nexo-secondary" data-nexo-voz>🎙 Voz</button><button type="button" class="nexo-primary" data-nexo-enviar>Enviar</button></div><div class="nexo-quick-toggle"><span>Más acciones de NEXO</span><button type="button" data-nexo-toggle aria-label="Mostrar más acciones">+</button></div><div class="nexo-fab-actions nexo-extra-actions" data-nexo-extra hidden><button type="button" class="nexo-management nexo-wide" data-nexo-integral style="display:none">✦ Analizar todo e informar a Gerencia</button><button type="button" class="nexo-management" data-nexo-reporte style="display:none">▤ Generar reporte</button><button type="button" class="nexo-management" data-nexo-revision style="display:none">✓ Revisar sistema</button><button type="button" class="nexo-management nexo-wide" data-nexo-aviso style="display:none">⚠ Enviar alerta/notificación</button><button type="button" class="nexo-open" data-nexo-abrir>Abrir Centro Nexo IA</button></div></div>`;
    document.body.appendChild(p);document.body.appendChild(b);document.body.appendChild(dock);
    try{oculto=localStorage.getItem('efleet_nexo_fab_oculto')==='1';}catch(_){oculto=false;}aplicarOculto(oculto,b,p,dock);
    dock.onclick=()=>aplicarOculto(!oculto,b,p,dock);
    b.onclick=()=>{if(oculto)return;abierto=!abierto;p.classList.toggle('open',abierto);if(abierto){obtenerApi().then(()=>{estado('NEXO IA · mismo núcleo y poderes del Centro Inteligente');$$('[data-nexo-integral],[data-nexo-reporte],[data-nexo-revision],[data-nexo-aviso]',p).forEach(x=>x.style.display=puedeGestion()?'block':'none');}).catch(()=>estado('Nexo esperando conexión…'));}};
    $('.nexo-fab-close',p).onclick=()=>{abierto=false;p.classList.remove('open');};$('[data-nexo-enviar]',p).onclick=()=>preguntar($('#nexoFabInput')?.value);$('[data-nexo-voz]',p).onclick=iniciarVoz;$('[data-nexo-doc-flota]',p).onclick=()=>{prepararModoRapido('');preguntar('Muéstrame los documentos de mi flota');};$('[data-nexo-doc-vehiculos]',p).onclick=()=>{prepararModoRapido('');preguntar('Muéstrame los documentos de mis vehículos');};$('[data-nexo-combustible]',p).onclick=()=>{location.href='combustible.html';};$('[data-nexo-rut]',p).onclick=()=>prepararModoRapido('RUT');$('[data-nexo-patente]',p).onclick=()=>prepararModoRapido('PATENTE');const toggle=$('[data-nexo-toggle]',p),extras=$('[data-nexo-extra]',p);toggle.onclick=()=>{const abrir=extras.hidden;extras.hidden=!abrir;toggle.textContent=abrir?'−':'+';toggle.setAttribute('aria-label',abrir?'Ocultar acciones':'Mostrar más acciones');};$('[data-nexo-integral]',p).onclick=()=>preguntar('Nexo, analiza todo el sistema e informa a Gerencia');$('[data-nexo-reporte]',p).onclick=()=>preguntar('Nexo, genera un reporte de salud del sistema');$('[data-nexo-revision]',p).onclick=()=>preguntar('Nexo, ejecuta una revisión general del sistema');$('[data-nexo-aviso]',p).onclick=prepararAviso;$('[data-nexo-abrir]',p).onclick=abrirCentro;$('#nexoFabInput',p).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();preguntar(e.currentTarget.value);}});programarGesto();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',crear,{once:true});else crear();
})();
