(()=>{
  'use strict';
  if(window.__NEXO_FLOTANTE_4498__)return;window.__NEXO_FLOTANTE_4498__=true;
  if(window.self!==window.top)return;
  const pagina=(location.pathname.split('/').pop()||'').toLowerCase();
  if(['index.html','404.html','politica-privacidad.html','terminos-condiciones.html'].includes(pagina))return;
  const $=(s,r=document)=>r.querySelector(s), sleep=ms=>new Promise(r=>setTimeout(r,ms));
  let api=null,abierto=false,escuchando=null,ocupado=false;
  async function obtenerApi(){if(api)return api;const limite=Date.now()+12000;while(Date.now()<limite){if(window.ConexionFlotas){api=window.ConexionFlotas;return api;}await sleep(80);}throw new Error('NEXO_SIN_CONEXION');}
  function auth(){try{return api?.getAuth?.()||window.ConexionFlotas?.getAuth?.()||{};}catch(_){return{};}}
  function rolActual(){const u=auth().user||{};return String(u.ROL_ID||u.rol_id||u.ROL||u.rol||'').toUpperCase();}
  function puedeGestion(){return ['ROL-SYSADMIN','ROL-ADMIN','ROL-GERENCIA','ADMIN','GERENCIA'].includes(rolActual());}
  function estilo(){
    if($('#nexoFabStyle'))return;const st=document.createElement('style');st.id='nexoFabStyle';st.textContent=`
      @keyframes nexoSpin{to{transform:rotate(360deg)}}@keyframes nexoPulse{0%,100%{opacity:.55;transform:scale(.96)}50%{opacity:1;transform:scale(1.08)}}
      #nexoFab{position:fixed;right:18px;bottom:20px;width:80px;height:80px;border:0;border-radius:50%;padding:5px;background:#061b45;z-index:2147482000;cursor:pointer;filter:drop-shadow(0 10px 17px rgba(4,72,160,.4));transition:.18s transform,.18s filter;touch-action:manipulation;isolation:isolate}
      #nexoFab::before{content:'';position:absolute;inset:-5px;border-radius:50%;background:conic-gradient(from 0deg,#0a5fff,#42e8ff,#fff,#1677ff,#061b45,#42e8ff,#0a5fff);animation:nexoSpin 5.2s linear infinite;z-index:-2;box-shadow:0 0 18px #2bdcffaa,0 0 34px #087cff55}
      #nexoFab::after{content:'';position:absolute;inset:-1px;border-radius:50%;background:#061b45;z-index:-1;box-shadow:inset 0 0 0 2px #76efff99}
      #nexoFab:hover{transform:translateY(-3px) scale(1.045);filter:drop-shadow(0 13px 24px rgba(4,102,220,.55))}#nexoFab:hover::before{animation-duration:2.4s}
      #nexoFab.busy::before{animation-duration:.9s;box-shadow:0 0 24px #62f4ff,0 0 48px #0a7cffaa}#nexoFab.attention::before{animation:nexoSpin 2.6s linear infinite,nexoPulse 1.1s ease-in-out infinite}
      #nexoFab img{width:100%;height:100%;border-radius:50%;display:block;object-fit:cover;position:relative;z-index:1}
      #nexoFab .ia{position:absolute;right:-4px;bottom:0;background:#071a3b;color:#fff;border:2px solid #68dcff;border-radius:999px;font:800 10px/1 system-ui;padding:5px 6px;box-shadow:0 4px 10px #0005;z-index:3}
      #nexoFabPanel{position:fixed;right:18px;bottom:116px;width:min(410px,calc(100vw - 24px));max-height:min(690px,calc(100vh - 138px));display:none;flex-direction:column;overflow:hidden;background:#fff;border:1px solid #b8d7ee;border-radius:22px;box-shadow:0 24px 60px rgba(1,35,78,.28);z-index:2147481999;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#102a43}
      #nexoFabPanel.open{display:flex}.nexo-fab-head{display:flex;align-items:center;gap:10px;padding:12px 14px;background:linear-gradient(135deg,#062d63,#0b73d9);color:white}.nexo-fab-head img{width:46px;height:46px;border-radius:50%}.nexo-fab-head b{display:block;font-size:18px}.nexo-fab-head span{font-size:11px;opacity:.92}.nexo-fab-close{margin-left:auto;border:0;background:#ffffff25;color:#fff;border-radius:50%;width:34px;height:34px;font-size:20px;cursor:pointer}
      .nexo-fab-body{padding:12px;overflow:auto}.nexo-fab-status{padding:8px 10px;background:#eef7ff;border:1px solid #cce7ff;border-radius:12px;font-size:12px;margin-bottom:8px}.nexo-fab-powers{display:flex;gap:6px;overflow:auto;padding:0 0 8px}.nexo-power{white-space:nowrap;border:1px solid #c9e3f8;background:#f6fbff;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:700;color:#0b5aa7}
      .nexo-fab-chat{display:flex;flex-direction:column;gap:8px;max-height:270px;overflow:auto;padding:2px 0 9px}.nexo-msg{padding:9px 10px;border-radius:14px;font-size:13px;line-height:1.35;white-space:pre-wrap}.nexo-msg.nexo{background:#eef6ff;border:1px solid #cce3fb}.nexo-msg.user{background:#0b73d9;color:white;margin-left:32px}.nexo-msg.meta{background:#f7fafc;border:1px dashed #bfd2e0;font-size:11px;color:#526b7a}
      .nexo-fab-input{width:100%;min-height:76px;resize:vertical;border:1px solid #bfd4e5;border-radius:13px;padding:10px 11px;font:14px system-ui;box-sizing:border-box;outline:none}.nexo-fab-input:focus{border-color:#1d7fe0;box-shadow:0 0 0 3px #1d7fe022}.nexo-fab-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.nexo-fab-actions button{border:0;border-radius:12px;min-height:42px;padding:8px 10px;font-weight:750;cursor:pointer}.nexo-primary{background:#1878e5;color:#fff}.nexo-secondary{background:#eaf4ff;color:#0c5eb2}.nexo-management{background:#062d63!important;color:#fff}.nexo-open{grid-column:1/-1;background:#f0f4f8!important;color:#102a43}.nexo-wide{grid-column:1/-1}
      @media(max-width:640px){#nexoFab{width:66px;height:66px;right:12px;bottom:14px}#nexoFabPanel{right:12px;bottom:94px;width:calc(100vw - 24px);max-height:calc(100vh - 110px)}}@media print{#nexoFab,#nexoFabPanel{display:none!important}}
    `;document.head.appendChild(st);
  }
  function mensaje(texto,tipo='nexo'){const chat=$('#nexoFabChat');if(!chat)return;const d=document.createElement('div');d.className=`nexo-msg ${tipo}`;d.textContent=String(texto??'');chat.appendChild(d);chat.scrollTop=chat.scrollHeight;}
  function estado(texto){const n=$('#nexoFabStatus');if(n)n.textContent=texto;}
  function setOcupado(v){ocupado=v;$('#nexoFab')?.classList.toggle('busy',v);$$('#nexoFabPanel button').forEach(b=>{if(!b.classList.contains('nexo-fab-close'))b.disabled=v;});}
  function $$(s,r=document){return Array.from(r.querySelectorAll(s));}
  async function preguntar(texto){const q=String(texto||'').trim();if(!q||ocupado)return;mensaje(q,'user');const campo=$('#nexoFabInput');if(campo)campo.value='';estado('Nexo está analizando con el mismo núcleo del Centro Inteligente…');setOcupado(true);try{const a=await obtenerApi();const r=await a.request('officeAsk',{data:{MENSAJE:q,PREGUNTA:q,ORIGEN:'NEXO_FLOTANTE_WEB',CANAL:'CHAT_FLOTANTE',NIVEL_ANALISIS:'DETALLADO',CONSULTA_PREDETERMINADA:puedeGestion()?'NO':'SI'}});mensaje(r?.respuesta||'Nexo completó la consulta.');if(r?.datos?.tipo)mensaje(`Acción NEXO: ${r.datos.tipo}`,'meta');if(Array.isArray(r?.documentos)&&r.documentos.length)mensaje(`Documentos encontrados: ${r.documentos.length}. Puede abrir el Centro Nexo para visualizarlos con validación de permisos.`,'meta');if(Number(r?.datos?.alertas||0)>0||Number(r?.datos?.notificaciones||0)>0){const f=$('#nexoFab');f?.classList.add('attention');setTimeout(()=>f?.classList.remove('attention'),5000);}estado('NEXO IA · mismo núcleo y poderes del Centro Inteligente');}catch(e){mensaje(`No pude completar la acción: ${String(e?.message||e||'error')}`);estado('Nexo disponible · revise conexión o permisos');}finally{setOcupado(false);}}
  function iniciarVoz(){const campo=$('#nexoFabInput');if(!campo)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){mensaje('El navegador no expone reconocimiento de voz. Puede escribir aquí o usar Nexo IA en Android.');return;}try{escuchando?.abort?.();}catch(_){}const r=new Recognition();escuchando=r;r.lang='es-CL';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>estado('🎙 Nexo está escuchando…');r.onresult=e=>{const t=String(e.results?.[0]?.[0]?.transcript||'').trim();if(t){campo.value=t;preguntar(t);}};r.onerror=()=>estado('No se pudo reconocer la voz · puede escribir');r.onend=()=>{escuchando=null;};try{r.start();}catch(_){estado('Micrófono ocupado');}}
  function prepararAviso(){const campo=$('#nexoFabInput');if(!campo)return;campo.value='Nexo, envía una alerta y notificación a Gerencia: ';campo.focus();campo.setSelectionRange(campo.value.length,campo.value.length);estado('Escriba el mensaje y pulse Enviar. Nexo validará su rol y empresa.');}
  function abrirCentro(){location.href='oficina-virtual.html';}
  function crear(){estilo();const b=document.createElement('button');b.id='nexoFab';b.type='button';b.setAttribute('aria-label','Abrir Nexo IA');b.title='Nexo IA · Centro Inteligente';b.innerHTML='<img src="./nexo-ia-fab.png" alt="Nexo IA"><span class="ia">IA</span>';
    const p=document.createElement('section');p.id='nexoFabPanel';p.setAttribute('aria-label','Nexo IA');p.innerHTML=`<div class="nexo-fab-head"><img src="./nexo-ia-fab.png" alt=""><div><b>Nexo IA</b><span>Chat flotante · mismo núcleo del Centro Inteligente</span></div><button class="nexo-fab-close" type="button" aria-label="Cerrar">×</button></div><div class="nexo-fab-body"><div id="nexoFabStatus" class="nexo-fab-status">Conectando con Nexo…</div><div class="nexo-fab-powers"><span class="nexo-power">Preguntas</span><span class="nexo-power">Análisis</span><span class="nexo-power">Mantenciones</span><span class="nexo-power">Combustible</span><span class="nexo-power">Reportes</span><span class="nexo-power">Alertas</span><span class="nexo-power">Notificaciones</span></div><div id="nexoFabChat" class="nexo-fab-chat"><div class="nexo-msg nexo">Hola. Soy Nexo IA. Este chat flotante tiene el mismo núcleo, datos, funciones y permisos que el Centro Inteligente. Puedo responder, analizar, generar reportes y ejecutar acciones de gestión autorizadas.</div></div><textarea id="nexoFabInput" class="nexo-fab-input" placeholder="Escribe o dicta una orden para Nexo…"></textarea><div class="nexo-fab-actions"><button type="button" class="nexo-secondary" data-nexo-voz>🎙 Voz</button><button type="button" class="nexo-primary" data-nexo-enviar>Enviar</button><button type="button" class="nexo-management nexo-wide" data-nexo-integral style="display:none">✦ Analizar todo e informar a Gerencia</button><button type="button" class="nexo-management" data-nexo-reporte style="display:none">▤ Generar reporte</button><button type="button" class="nexo-management" data-nexo-revision style="display:none">✓ Revisar sistema</button><button type="button" class="nexo-management nexo-wide" data-nexo-aviso style="display:none">⚠ Enviar alerta/notificación</button><button type="button" class="nexo-open" data-nexo-abrir>Abrir Centro Nexo IA</button></div></div>`;
    document.body.appendChild(p);document.body.appendChild(b);
    b.onclick=()=>{abierto=!abierto;p.classList.toggle('open',abierto);if(abierto){obtenerApi().then(()=>{estado('NEXO IA · mismo núcleo y poderes del Centro Inteligente');$$('[data-nexo-integral],[data-nexo-reporte],[data-nexo-revision],[data-nexo-aviso]',p).forEach(x=>x.style.display=puedeGestion()?'block':'none');}).catch(()=>estado('Nexo esperando conexión…'));}};
    $('.nexo-fab-close',p).onclick=()=>{abierto=false;p.classList.remove('open');};$('[data-nexo-enviar]',p).onclick=()=>preguntar($('#nexoFabInput')?.value);$('[data-nexo-voz]',p).onclick=iniciarVoz;$('[data-nexo-integral]',p).onclick=()=>preguntar('Nexo, analiza todo el sistema e informa a Gerencia');$('[data-nexo-reporte]',p).onclick=()=>preguntar('Nexo, genera un reporte de salud del sistema');$('[data-nexo-revision]',p).onclick=()=>preguntar('Nexo, ejecuta una revisión general del sistema');$('[data-nexo-aviso]',p).onclick=prepararAviso;$('[data-nexo-abrir]',p).onclick=abrirCentro;$('#nexoFabInput',p).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();preguntar(e.currentTarget.value);}});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',crear,{once:true});else crear();
})();
